CREATE TYPE "PsebStatus" AS ENUM ('DRAFT', 'SUBMITTED', 'PRIMARY_APPROVED', 'PAYMENT_PENDING', 'PAYMENT_SUBMITTED', 'APPROVED', 'REJECTED', 'REQUIRES_INFO');

CREATE TABLE IF NOT EXISTS "PsebCompanyRegistration" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "companyName" TEXT NOT NULL,
  "companyType" TEXT NOT NULL,
  "businessNtn" TEXT,
  "registrationDate" TIMESTAMP(3),
  "servicesOffered" JSONB,
  "serviceDescription" TEXT,
  "address" TEXT,
  "city" TEXT,
  "province" TEXT,
  "phone" TEXT,
  "email" TEXT,
  "website" TEXT,
  "totalEmployees" INTEGER,
  "directors" JSONB,
  "ntnCertificateUrl" TEXT,
  "cnicDirectorsUrl" JSONB,
  "moaUrl" TEXT,
  "aoaUrl" TEXT,
  "form29Url" TEXT,
  "form2Url" TEXT,
  "incCertificateUrl" TEXT,
  "partnershipDeedUrl" TEXT,
  "formCUrl" TEXT,
  "bankStatementUrl" TEXT,
  "status" "PsebStatus" NOT NULL DEFAULT 'DRAFT',
  "psebRefNumber" TEXT,
  "certificateUrl" TEXT,
  "adminNotes" TEXT,
  "fee" DOUBLE PRECISION,
  "paymentReceiptUrl" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PsebCompanyRegistration_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "PsebCallCenterRegistration" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "companyName" TEXT NOT NULL,
  "companyType" TEXT NOT NULL,
  "businessNtn" TEXT,
  "registrationDate" TIMESTAMP(3),
  "seatingCapacity" INTEGER,
  "numberOfShifts" INTEGER,
  "dialerSystem" TEXT,
  "pbxSystem" TEXT,
  "internetBandwidth" TEXT,
  "serviceType" JSONB,
  "clientCountries" JSONB,
  "serviceDescription" TEXT,
  "address" TEXT,
  "city" TEXT,
  "province" TEXT,
  "floorArea" TEXT,
  "phone" TEXT,
  "email" TEXT,
  "website" TEXT,
  "totalEmployees" INTEGER,
  "directors" JSONB,
  "ntnCertificateUrl" TEXT,
  "cnicDirectorsUrl" JSONB,
  "moaUrl" TEXT,
  "aoaUrl" TEXT,
  "form29Url" TEXT,
  "incCertificateUrl" TEXT,
  "partnershipDeedUrl" TEXT,
  "formCUrl" TEXT,
  "bankStatementUrl" TEXT,
  "officePhotosUrl" JSONB,
  "equipmentListUrl" TEXT,
  "status" "PsebStatus" NOT NULL DEFAULT 'DRAFT',
  "psebRefNumber" TEXT,
  "provisionalLetterUrl" TEXT,
  "certificateUrl" TEXT,
  "inspectionDate" TIMESTAMP(3),
  "inspectionNotes" TEXT,
  "adminNotes" TEXT,
  "fee" DOUBLE PRECISION,
  "paymentReceiptUrl" TEXT,
  "isBranch" BOOLEAN NOT NULL DEFAULT false,
  "mainOfficeId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PsebCallCenterRegistration_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "PsebCompanyRegistration_userId_idx" ON "PsebCompanyRegistration"("userId");
CREATE INDEX IF NOT EXISTS "PsebCompanyRegistration_status_idx" ON "PsebCompanyRegistration"("status");
CREATE INDEX IF NOT EXISTS "PsebCallCenterRegistration_userId_idx" ON "PsebCallCenterRegistration"("userId");
CREATE INDEX IF NOT EXISTS "PsebCallCenterRegistration_status_idx" ON "PsebCallCenterRegistration"("status");

ALTER TABLE "PsebCompanyRegistration" ADD CONSTRAINT "PsebCompanyRegistration_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PsebCallCenterRegistration" ADD CONSTRAINT "PsebCallCenterRegistration_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
